### PR TITLE
Update CSI to v2.2.0 with CPI

### PR DESCRIPTION
**Pull request by Kissy**

### CODE REVIEW

**Comment by mylesagray** [comment]
@Kissy im reviewing PRs #3 and #4 this week which will supersede and provide this functionality - my preference is to merge those instead - does that work for you?

**Comment by Kissy** [comment]
@mylesagray I tried using the code from PRs #3 and #4 unfortunately there was some issues with it (changing secret name was not working for instance) and the service account was not split for controller & node.

I went from those 2 PRs and added few changes to use the latest version of CSI & CPI with the changes required in deployment.

**Comment by MaxRink** [comment]
> @mylesagray I tried using the code from PRs #3 and #4 unfortunately there was some issues with it (changing secret name was not working for instance) and the service account was not split for controller & node.
> 
> I went from those 2 PRs and added few changes to use the latest version of CSI & CPI with the changes required in deployment.

the serviceAccount should be split, but yeah, the override currently doesnt work.

**Comment by MaxRink** [comment]
@Kissy i think i fixed the serviceaccount thingie.

**Comment by mylesagray** [comment]
@Kissy closing in favour of #4 that was just merged.

**Pull request closed without merging**
