### PR TITLE
use existing config for cpi

### PR DESCRIPTION
**Pull request by farodin91**

### CODE REVIEW

**Comment by sathieu** [comment]
The CSI part is quite similar to https://github.com/vsphere-tmm/helm-charts/pull/56.

I think you should bump minor version (this is a new feature).

**Comment by farodin91** [comment]
@sathieu  CSI part is removed

**Comment by farodin91** [comment]
@sathieu Would you like to review it again?

**Comment by sathieu** [comment]
@farodin91 This looks good for me. But I'm only a contributor to this repo.

**Pull request merged**
